version: "3"
services:
  api:
    build: .
    image: api_django_python_hello-world_rbac
    container_name: api_django_python_hello-world_rbac
    ports:
      - "6060:6060"
    env_file:
      - .env
